apiVersion: apps/v1
kind: Deployment
metadata:
  name: davidbourgault-ca
  labels:
    app.kubernetes.io/name: ca.davidbourgault.www
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ca.davidbourgault.www
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ca.davidbourgault.www
    spec:
      containers:
      - name: davidbourgault-ca
        image: gcr.io/davidbourgault-ca/website:latest
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 500m
            memory: 256M
          limits:
            cpu: 500m
            memory: 256M

---

apiVersion: v1
kind: Service
metadata:
  name: davidbourgault-ca
  labels:
    app.kubernetes.io/name: ca.davidbourgault.www
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ca.davidbourgault.www
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: davidbourgault-ca
  annotations:
    cert-manager.io/issuer: letsencrypt
  labels:
    app.kubernetes.io/name: ca.davidbourgault.www
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - davidbourgault.ca
    secretName: davidbourgault-letsencrypt-cert
  rules:
  - host: davidbourgault.ca
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: davidbourgault-ca
            port: 
              number: 80